env:
CODECOV_TOKEN="5c242565-bcfb-4ceb-af1c-2fdf28f985ac"

language: java
jdk:
- oraclejdk8
sudo: false
script: mvn clean verify
script: "mvn cobertura:cobertura"
after_success:
- bash <(curl -s https://codecov.io/bash)



