

package br.com.utilitarios;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author FELIPE
 */

public class ModulosSistemas {
    public int id;
    public String nomeModulo;
    
    public static final int AvisosAcessandoSistema = 100001;
    public static final int Estados = 100002;
    public static final int Bairros = 100003;
    public static final int Logradouros = 100004;
    public static final int Selic = 100005;
    public static final int EstadoCivil = 100006;
    public static final int Pessoas = 100007;
    public static final int Orgaos = 100008;
    public static final int Unidades = 100009;
    public static final int PlanodeContas = 100010;
    public static final int ParametrosComuns = 100011;
    public static final int Funcoes = 100012;
    public static final int SubFuncoes = 100013;
    public static final int Programas = 100014;
    public static final int SubProgramas = 100015;
    public static final int Acoes = 100016;
    public static final int FontedeRecursos = 100017;
    public static final int FormasdePagamento = 100018;
    public static final int TiposdeReceitaDespesaExtra = 100019;
    public static final int Moedas = 100020;
    public static final int TiposdePatrimonio = 100021;
    public static final int AssuntosdeContratos = 100022;
    public static final int TiposdeObras = 100023;
    public static final int TiposdeArrecadacao = 100024;
    public static final int Secoes = 100025;
    public static final int SecoesUsuarios = 100026;
    public static final int Combustiveis = 100027;
    public static final int MarcasdeVeiculos = 100028;
    public static final int ModelosdeVeiculos = 100029;
    public static final int TiposdeOcorrenciasdeTransito = 100030;
    public static final int TiposdeVeiculos = 100031;
    public static final int SituacaodosVeiculos = 100032;
    public static final int SelecaodeSecoes = 100033;
    public static final int GruposdeMateriais = 100034;
    public static final int SubGruposdeMateriais = 100035;
    public static final int TiposdeCertidoesNegativas = 100036;
    public static final int Materiais = 100037;
    public static final int CertidoesdosFornecedores = 100038;
    public static final int Veiculos = 100039;
    public static final int ConsultaComprasMaterial = 100040;
    public static final int ConsultaNotasFiscaisdoMaterial = 100041;
    public static final int SindicatosFuncionais = 100042;
    public static final int TiposdeDireitosaReceber = 100043;
    public static final int ModalidadesdeLicitacao = 100044;
    public static final int Nacionalidades = 100045;
    public static final int GraudeInstrucao = 100046;
    public static final int INSS = 100047;
    public static final int IRRF = 100048;
    public static final int Patrimonio = 100049;

    public static final int PatrimonioValores = 100050;
    public static final int Municipios = 100051;
    public static final int Bancos = 100052;
    public static final int AssinaturasGestor = 100053;
    public static final int AssinaturasControladorInterno = 100054;
    public static final int Classesdepatrimonio = 100055;
    public static final int PatrimonioResponsaveis = 100056;
    public static final int CategoriasFuncionais = 100057;
    public static final int TiposdeAdmissaoFuncionais = 100058;
    public static final int CBO = 100059;
    public static final int CARGOS = 100060;
    public static final int CARGOSVALORES = 100061;
    public static final int Horarios = 100062;
    public static final int CodigosdeAcumulosparaCedulaC = 100063;
    public static final int FormulasdeCalculo = 100064;
    public static final int TiposdeFolha = 100065;
    public static final int SituacoesFuncionais = 100066;
    public static final int TiposdeLicencas = 100067;
    public static final int TiposdeProventos = 100068;
    public static final int TiposdeDescontos = 100069;
    public static final int Eventos = 100070;
    public static final int RecibosdePagamentoRH = 100071;
    public static final int VinculosEmpregaticios = 100072;
    public static final int CausasdeRescisoes = 100073;
    public static final int ReferenciasdosFuncionarios = 100074;
    public static final int CARGOSNIVEIS = 100075;
    public static final int CentrosdeCustos = 100076;
    public static final int TiposdeAdmissoesFuncionariosPublicos = 100077;
    public static final int TiposdeDesligamentosRH = 100078;
    public static final int Dadosfuncionais = 100079;
    public static final int Concursos = 100080;
    public static final int ConcursosVagas = 100081;
    public static final int ConcursosAprovados = 100082;
    public static final int DadosdePensionista = 100083;
    public static final int ConsultaFuncionariosporSecao = 100084;
    public static final int ConsultaFuncionariosporCargo = 100085;
    public static final int TiposdeDeficienciasFisicas = 100086;
    public static final int FormacaoAcademica = 100087;
    public static final int Funcionarios = 100088;
    public static final int FuncionariosCentrodeCusto = 100089;
    public static final int OutrosVinculosdeINSS = 100090;
    public static final int Licencas = 100091;
    public static final int Dependentes = 100092;
    public static final int FuncionariosdeFerias = 100093;
    public static final int LancamentosMensaisdeEventos = 100094;
    public static final int CalculodaFolha = 100095;
    public static final int CARGOSCLASSES = 100096;
    public static final int UnidadesdeMedidasdeObras = 100097;
    public static final int CNAE = 100098;
    public static final int Eventoscontabeis = 100099;
    public static final int SituacaoPatrimonio = 100100;
    public static final int AssinaturasEspecificas = 100101;
    public static final int AgenciasBancarias = 100102;

    public static final int AssuntosdeProcessos = 1300001;
    public static final int Correspondencias = 1300002;
    public static final int Processos = 1300003;
    public static final int EnvioProcessos = 1300004;
    public static final int RecebimentoProcessos = 1300005;
    public static final int MovimentosProcessos = 1300006;
    public static final int FornecedoresdoProcesso = 1300007;
    public static final int ParametrosProtocolo = 1300008;
    public static final int MovimentosCorrespondencias = 1300009;
    public static final int EnvioCorrespondencias = 1300010;
    public static final int RecebimentoCorrespondencias = 1300011;
    public static final int PreProcessos = 1300012;


    public static final int OrcamentoLeis = 1100002;
    public static final int AutorizacaoOrcamentaria = 1100003;
    public static final int OrcamentoDotacoes = 1100004;
    public static final int OrcamentoReceitasPrevistas = 1100005;
    public static final int OrcamentoTotalizaDespesas = 1100006;
    public static final int HistoricosPadroes = 1100007;
    public static final int Licitacao = 1100008;
    public static final int Obras = 1100009;
    public static final int Contratos = 1100010;
    public static final int DividaFundada = 1100011;
    public static final int MovimentosdoAtivoRealizavel = 1100012;
    public static final int PreEmpenhos = 1100013;
    public static final int Empenhos = 1100014;
    public static final int EmpenhosNotasFiscais = 1100015;
    public static final int EmpenhosLiquidacaoEstorno = 1100016;
    public static final int EmpenhosAnulacao = 1100017;
    public static final int SubEmpenhos = 1100018;
    public static final int OrcamentoPPAIndicadoresdeProgramas = 1100019;
    public static final int OrcamentoPPAPlanoPlurianual = 1100020;
    public static final int Suplementacoes = 1100021;
    public static final int RestosEmpenhos = 1100022;
    public static final int VariacoesPatrimoniais = 1100023;
    public static final int MovimentosdasVariacoesPatrimoniais = 1100024;
    public static final int ParametrosContabilidade = 1100025;
    public static final int ParametrosdosOrgaos = 1100026;
    public static final int Reducoes = 1100027;
    public static final int FichaOrcamentaria = 1100028;
    public static final int GerarBalancete = 1100029;
    public static final int ReceitaExtraOrcamentaria = 1100030;
    public static final int AlienacaodeBens = 1100031;
    public static final int AplicacaoFinanceira = 1100032;
    public static final int Tiposdesuplementacao = 1100033;
    public static final int LancamentosContabeis = 1100034;
    public static final int RestosAnulacaodeEmpenhos = 1100035;
    public static final int ImpressaoGeraldeCheques = 1100036;
    public static final int MovimentosContabeis = 1100037;
    public static final int AbrirnovoOrcamento = 1100038;
    public static final int CaracteristicasPeculiardosEmpenhos = 1100039;
    public static final int GruposdeReceitaDespesaExtra = 1100040;
    public static final int CancelamentosExtraOrcamentarios = 1100041;
    public static final int LimitesdeSuplementacoes = 1100042;
    public static final int CaracteristicasPeculiardaReceita = 1100043;
    //public static final int  = 1100044;
    public static final int DireitosaReceber = 1100045;
    public static final int LancamentosContabeisdoSistema = 1100046;
    public static final int Convenios = 1100047;
    public static final int ParticipantesdeConvenios = 1100048;
    public static final int OrdensdePagamento = 1100049;
    public static final int Retencoes = 1100050;
    public static final int PreOrdensdePagamentoQuitacao = 1100051;
    public static final int PreOrdensdePagamento = 1100052;
    public static final int EmpenhosLiquidacao = 1100053;
    public static final int EmpenhosdeRestosLiquidacao = 1100054;
    public static final int RestosPreOrdensdePagamento = 1100055;
    public static final int RestosPreOrdensdePagtoQuitacao = 1100056;
    public static final int RestosOrdensdePagamento = 1100057;
    public static final int EstornodeOrdensdePagamentoGuiasdeRecolhimento = 1100058;
    public static final int ContabilidadeArrecadacao = 1100059;
    public static final int EstornodeArrecadacao = 1100060;
    public static final int ContabilidadeConciliacaoBancaria = 1100061;
    public static final int ContabilidadeTransferenciasBancarias = 1100062;
    public static final int PreOrdensdePagamentoDespesaExtra = 1100063;
    public static final int PreOrdensdePagamentoDespesaExtraQuitacao = 1100064;
    public static final int DespesaExtraOrcamentaria = 1100065;
    public static final int RestosGuiadeRecolhimento = 1100066;
    public static final int ContabilidadeCheques = 1100067;
    public static final int ContabilidadeCompensacaodeCheques = 1100068;
    public static final int RemecasBancarias = 1100069;

    public static final int Abastecimentos = 1400001;
    public static final int ManutencoesemVeiculos = 1400002;
    public static final int EmpenhosFrotas = 1400003;
    public static final int DeslocamentosdeVeiculos = 1400004;
    public static final int ParametrosFrotas = 1400005;
    public static final int Ocorrenciasdetransito = 1400006;


    public static final int OutraPrevidencia = 1500001;
    public static final int ExpressoesSQL = 1500002;
    public static final int UFIR = 1500003;
    public static final int GPSFPAS = 1500004;
    public static final int ValeTransporteValeRefeicao = 1500005;
    public static final int TabeladeAbatimentodeFaltas = 1500006;
    public static final int TiposdeAtos = 1500007;
    public static final int TiposdeMovimentacoesdepessoal = 1500008;
    public static final int DuplicarDadosFuncionais = 1500009;
    public static final int DuplicarumaReferencia = 1500010;
    public static final int CedulaC = 1500011;
    public static final int ConsultaHistoricoFerias = 1500012;
    public static final int Rescisoes = 1500013;
    public static final int VencimentosVariaveis = 1500014;
    public static final int Cadastrodeprestadoresdeservico = 1500015;
    public static final int PrestadorServicosMovimentacao = 1500016;
    public static final int EmpenhosdaFolha = 1500017;
    public static final int MovimentacaodePessoal = 1500018;
    public static final int CompensacaocomoINSS = 1500019;
    public static final int ParametrosFolha = 1500020;
    public static final int GPS = 1500021;
    public static final int Fechamentomensal = 1500022;
    public static final int GerarEmpenhosparaContabilidade = 1500023;
    public static final int AlteracoesdeChavesparaGoias = 1500024;
    public static final int CentrodeCustodePagamento = 1500025;

    public static final int ItensdaNotaFiscal = 1600001;
    public static final int MovimentacaodoEstoque = 1600002;
    public static final int AcertodeEstoque = 1600003;
    public static final int EntradanoEstoque = 1600004;
    public static final int SaidadoEstoque = 1600005;
    public static final int EmprestimosDevolucoesentreCentrosdeCusto = 1600006;
    public static final int EstoqueporSecao = 1600007;
    public static final int RequisicaodeMateriais = 1600008;
    public static final int RequisicaodeMateriaisItens = 1600009;
    public static final int BaixasemRequisicoesdeMateriais = 1600010;
    public static final int SolicitacaodeCompras = 1600011;
    public static final int SolicitacaodeComprasItens = 1600012;
    public static final int NotasFiscais = 1600013;
    public static final int NotasFiscaisItens = 1600014;
    public static final int RequisicaodeCompras = 1600015;
    public static final int RequisicaodeComprasItens = 1600016;
    public static final int CompraRapida = 1600017;
    public static final int ProcessodeComprasGeral = 1600018;
    public static final int ProcessodeComprasSolicitacoes = 1600019;
    public static final int ProcessodeComprasItens = 1600020;
    public static final int ProcessodeComprasFornecedores = 1600021;
    public static final int ProcessodeComprasCotacoes = 1600022;
    public static final int TiposdeLicitacoes = 1600023;

    public static final int CadastrosTributos = 1200001;
    public static final int CadastrosRubricas = 1200002;
    public static final int Tiposdesociedades = 1200003;
    public static final int Fiscais = 1200004;
    public static final int UFM = 1200005;
    public static final int TiposdeServicos = 1200006;
    public static final int Contribuintes = 1200007;
    public static final int ContribuintesFinanceiros = 1200008;
    public static final int ContribuintesLancamentosQuitacoes = 1200009;
    public static final int NotasFiscaisEmitidasporContribuintes = 1200010;
    public static final int EmitirAlvaraparaContribuintes = 1200011;
    public static final int CadastrosUsuariosNotaAvulsa = 1200012;
    public static final int Imoveis = 1200013;
    public static final int ImoveisCaracteristicas = 1200014;
    public static final int ImoveisFinanceiros = 1200015;
    public static final int ImoveisLancamentosQuitacao = 1200016;
    public static final int ImoveisGerarDAM = 1200017;
    public static final int ImpressaodeDeclaracaodeIsento = 1200018;
    public static final int PlantadeValoresdeIPTUNormal = 1200019;
    public static final int PlantadeValoresdeIPTUZoneamento = 1200020;
    public static final int PlantadeValoresdeIPTULogradouro = 1200021;
    public static final int PlantadeValoresdeIPTUZonaLogradouros = 1200022;
    public static final int InformacoesTerrenoIPTU = 1200023;
    public static final int InformacoesEdificacaoIPTU = 1200024;
    public static final int ItensBasicosIPTU = 1200025;
    public static final int AliquotasIPTU = 1200026;
    public static final int AliquotasIPTUConstrucao = 1200027;
    public static final int DescontosdeIPTUporCondicoes = 1200028;
    public static final int VencimentoParcelasIPTU = 1200029;
    public static final int ValoresTSUporm2 = 1200030;
    public static final int ValoresConstrucaoporTipo = 1200031;
    public static final int PlantadeValoresRurais = 1200032;
    public static final int InformacoesImoveisItens = 1200033;
    public static final int InformacoesImoveisSubItens = 1200034;
    public static final int FatordeCorrecaodeGlebas = 1200035;
    public static final int TabeladeTaxadeIluminacaoPublica = 1200036;
    public static final int TSUporFormula = 1200037;
    public static final int VencimentosAlvaraAnual = 1200038;
    public static final int CadastrosTaxas = 1200039;
    public static final int TiposdeTransmissoesITBI = 1200040;
    public static final int TiposdeIsencoes = 1200041;
    public static final int TabeladeAnistiaFiscal = 1200042;
    public static final int CadastrosDespesasMapaApuracaodeDespesas = 1200043;
    public static final int TabeladeMultaseJurosporTributo = 1200044;
    public static final int FatordeLocalizacaodeTaxas = 1200045;
    public static final int ExtratodoContribuinte = 1200046;
    public static final int TabelaMensagensExtranoDAM = 1200047;
    public static final int Isencoesdecontribuintes = 1200048;
    public static final int TiposdeTarefas = 1200049;
    public static final int FinalidadesdeCND = 1200050;
    public static final int ManutencaoCertidoesNegativas = 1200051;
    public static final int GerarDAMsdeIPTUdetodos = 1200052;
    public static final int GerarDAMsdeISSdetodos = 1200053;
    public static final int GerarDAMsdeIPTUparaCarne = 1200054;
    public static final int DAMSdeITBI = 1200055;
    public static final int DAMSdeITBIRural = 1200056;
    public static final int DAMSdeTaxas = 1200057;
    public static final int DAMSdeISS = 1200058;
    public static final int DAMSdeISSporPeriodo = 1200059;
    public static final int DAMSdeTaxadeAlvaraTodos = 1200060;
    public static final int NotaAvulsaManutencao = 1200061;
    public static final int NotaAvulsaManutencaonositens = 1200062;
    public static final int BlocosdeNotasFiscais = 1200063;
    public static final int CancelamentodeBlocosdeNotasFiscais = 1200064;
    public static final int OrdensdeServico = 1200065;
    public static final int OrdensdeServicodePosturas = 1200066;
    public static final int RocagemdeLotes = 1200067;
    public static final int AutodeInfracaodeContribuintes = 1200068;
    public static final int GuiadeFiscalizacao = 1200069;
    public static final int GuiadeFiscalizacaoManutencaoemitens = 1200070;
    public static final int GuiadeAtualizacaoFiscal = 1200071;
    public static final int GuiadeAtualizacaoFiscalManutencaoemitens = 1200072;
    public static final int ProcessosdeContribuintes = 1200073;
    public static final int MovimentacaodeProcessosdeContribuintes = 1200074;
    public static final int ProcessosdeImoveis = 1200075;
    public static final int MovimentacaodeProcessosdeImoveis = 1200076;
    public static final int ProcessosdePessoas = 1200077;
    public static final int MovimentacaodeProcessosdePessoas = 1200078;
    public static final int RegistrodeMarcas = 1200079;
    public static final int ParcelamentodeISS = 1200080;
    public static final int ParcelamentodeISSManutencaoemitens = 1200081;
    public static final int ParcelamentodeIPTU = 1200082;
    public static final int ParcelamentodeIPTUManutencaoemitens = 1200083;
    public static final int ImpressaodeCertidoesNegativas = 1200084;
    public static final int ImpressaodeEscriturasdedoacaodeImoveis = 1200085;
    public static final int ImpressaodeEscriturasdecompraevendadeImoveis = 1200086;
    public static final int MapadeApuracaodeDespesas = 1200087;
    public static final int TSUColetadelixo = 1200088;
    public static final int ValidarCertidaoNegativa = 1200089;
    public static final int IsencoesdeImoveis = 1200090;
    public static final int MovimentoNulodeISS = 1200091;
    public static final int DAMsAvulsosdeIPTU = 1200092;
    public static final int DAMsAvulsosdeTaxas = 1200093;
    public static final int DAMsLivres = 1200094;
    public static final int DocumentosdeArrecadacao = 1200095;
    public static final int BaixaManualdeDams = 1200096;
    public static final int BaixaAutomaticadeDams = 1200097;
    public static final int DividaEliminada = 1200098;
    public static final int ProcuraDívidaTextos = 1200099;
    public static final int DividaAtivaPreparaparaInscricao = 1200100;
    public static final int DividaAtivaLivros = 1200101;
    public static final int DividaAtivaCertidoesIPTU = 1200102;
    public static final int DividaAtivaCertidoesIPTUReferencias = 1200103;
    public static final int DividaAtivaInscricaoIPTU = 1200104;
    public static final int DividaAtivaCertidoesContribuintes = 1200105;
    public static final int DividaAtivaCertidoesContribuintesReferencias = 1200106;
    public static final int DividaAtivaInscricaoTaxaAlvara = 1200107;
    public static final int ParametrosSAM = 1200108;
    public static final int RelatoriosIPTUCarnes = 1200109;
    public static final int RelatoriosIPTUImpressaodeDAMs = 1200110;
    public static final int RelatoriosISSCarnes = 1200111;
    public static final int InformacoesImoveisGrupos = 1200112;
    public static final int Zoneamentos = 1200113;
    public static final int Loteamentos = 1200114;
    public static final int Condominios = 1200115;
    public static final int TributosReceitacontabeis = 1200116;
    public static final int ComposicaodoIPTU = 1200117;
    public static final int GerarDAMsdeIPTU = 1200118;
    public static final int ValorM2deConstrucaoporArea = 1200119;
    public static final int PlantadeValoresdeRocagemdeLotes = 1200120;
    public static final int LegislacaodeNotaAvulsa = 1200121;
    public static final int FecharExercicio = 1200122;
    public static final int Alvaradeconstrucao = 1200123;
    public static final int Fatordecorrecaoporareacontruida = 1200124;
    public static final int Valorm2deconstrucaoporCondicoes = 1200125;
    public static final int Fatordecorrecaoporcondicoes = 1200126;
    public static final int DividasSuspensas = 1200127;
    public static final int FinanceirosPessoas = 1200128;
    public static final int ValorM2ConstrucaoPontos = 1200129;
    public static final int ImoveisRurais = 1200130;
    public static final int DAMsTaxasEventuais = 1200131;
    public static final int NFSeEfetivarContribuintes = 1200132;

    public static final int Imagemdolocal = 1700001;
    public static final int MovimentacaodoPatrimonio = 1700002;
    public static final int PesquisaTermodeEntrega = 1700003;
    public static final int TermodeEntregadeBens = 1700004;
    public static final int ParametrosPatrimonio = 1700005;

    public static final int FinanceiroParametros = 1800001;
    public static final int CadastrosTiposdeReceitas = 1800002;
    public static final int CadastrosTiposdeDespesas = 1800003;
    public static final int CadastrosFormasdePagamento = 1800004;
    public static final int FinanceiroContasbancarias = 1800005;
    public static final int Receitas = 1800008;
    public static final int Despesas = 1800011;
    public static final int TransferenciasBancarias = 1800012;
    public static final int ConsultaContasBancarias = 1800013;
    public static final int PrevisaodeReceitas = 1800014;
    public static final int PrevisaodeDespesas = 1800015;
    public static final int Compensacaodecheques = 1800016;
    public static final int RelatoriosDespesasGeralporPeriodo = 1800019;
    public static final int RelatoriosDespesasPrevistasporPeriodo = 1800020;
    public static final int RelatoriosDespesasGeralporPeriodoFornecedor = 1800021;
    public static final int RelatoriosDespesasporTipodeDespesa = 1800022;
    public static final int RelatoriosReceitasGeralporPeriodo = 1800023;
    public static final int RelatoriosReceitasPrevistasporPeriodo = 1800024;
    public static final int RelatoriosReceitasExtratoporTipo = 1800025;
    public static final int RelatoriosExtratoBancario = 1800026;
    public static final int RelatoriosImpressaodeCheques = 1800027;
    public static final int RelatoriosSaldosBancarios = 1800028;
    public static final int RelatoriosConciliacaoBancaria = 1800029;
    public static final int RelatoriosPrevisaoGeral = 1800030;
    public static final int RelatoriosPrevisaoDespesa = 1800031;
    public static final int RelatoriosDespesasResumoTipo = 1800032;       
    public static final int RelatoriosDespesasPeriodoContaBancaria = 1800033;       
    public static final int RelatoriosDespesasPeriodoFonteRecurso = 1800034;
    public static final int RelatoriosReceitasPeriodoFonteRecurso = 1800035;

    public ModulosSistemas() {
    }

    public ModulosSistemas(String id, String nomeModulo) {
        this.id = UteisMetodos.nz(id, 0);
        this.nomeModulo = nomeModulo;
    }
    public ModulosSistemas(int id, String nomeModulo) {
        this.id = id;
        this.nomeModulo = nomeModulo;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getNomeModulo() {
        return nomeModulo;
    }

    public void setNomeModulo(String nomeModulo) {
        this.nomeModulo = nomeModulo;
    }
    
    public List<ModulosSistemas> getListaCadstros(){
        List<ModulosSistemas> list = new ArrayList<ModulosSistemas>();

        list.add(new ModulosSistemas("01000000","ACESSAR O SISTEMA ADMINISTRATIVO"));
        list.add(new ModulosSistemas("01100000","ACESSAR O SISTEMA DE CONTABILIDADE"));
        list.add(new ModulosSistemas("01200000","ACESSAR O SISTEMA DE ARRECADACAO"));
        list.add(new ModulosSistemas("01300000","ACESSAR O SISTEMA DE PROTOCOLO"));
        list.add(new ModulosSistemas("01400000","ACESSAR O SISTEMA DE FROTAS"));
        list.add(new ModulosSistemas("01500000","ACESSAR O SISTEMA DE RH"));
        list.add(new ModulosSistemas("01600000","ACESSAR O SISTEMA DE COMPRAS/ALMOXARIFADO"));
        list.add(new ModulosSistemas("01700000","ACESSAR O SISTEMA DE PATRIMONIO"));
        list.add(new ModulosSistemas("01800000","ACESSAR O SISTEMA DE FINANCEIRO"));
        list.add(new ModulosSistemas("02100000","ACESSAR O SISTEMA DE SIM"));

        list.add(new ModulosSistemas("00100001","AVISOS DO SISTEMA"));
        list.add(new ModulosSistemas("00100002","ESTADOS"));
        list.add(new ModulosSistemas("00100003","BAIRROS"));
        list.add(new ModulosSistemas("00100004","LOGRADOUROS"));
        list.add(new ModulosSistemas("00100005","SELIC"));
        list.add(new ModulosSistemas("00100006","ESTADO CIVIL"));
        list.add(new ModulosSistemas("00100007","PESSOAS"));
        list.add(new ModulosSistemas("00100008","ORGAOS"));
        list.add(new ModulosSistemas("00100009","UNIDADES"));
        list.add(new ModulosSistemas("00100010","PLANO DE CONTAS"));
        list.add(new ModulosSistemas("00100011","PARAMETROS COMUNS"));
        list.add(new ModulosSistemas("00100012","FUNCOES"));
        list.add(new ModulosSistemas("00100013","SUBFUNCOES"));
        list.add(new ModulosSistemas("00100014","PROGRAMAS"));
        list.add(new ModulosSistemas("00100015","SUBPROGRAMAS"));
        list.add(new ModulosSistemas("00100016","ACOES"));
        list.add(new ModulosSistemas("00100017","FONTE DE RECURSOS"));
        list.add(new ModulosSistemas("00100018","FORMAS DE PAGAMENTO"));
        list.add(new ModulosSistemas("00100019","TIPOS DE RECEITA/DESPESA EXTRA"));
        list.add(new ModulosSistemas("00100020","MOEDAS"));
        list.add(new ModulosSistemas("00100021","TIPOS DE PATRIMONIO"));
        list.add(new ModulosSistemas("00100022","ASSUNTOS DE CONTRATOS"));
        list.add(new ModulosSistemas("00100023","TIPOS DE OBRAS"));
        list.add(new ModulosSistemas("00100024","TIPOS DE ARRECADACAO"));
        list.add(new ModulosSistemas("00100025","SECOES"));
        list.add(new ModulosSistemas("00100026","SECOES-USUARIOS"));
        list.add(new ModulosSistemas("00100027","COMBUSTIVEIS"));
        list.add(new ModulosSistemas("00100028","MARCAS DE VEICULOS"));
        list.add(new ModulosSistemas("00100029","MODELOS DE VEICULOS"));
        list.add(new ModulosSistemas("00100030","TIPOS DE OCORRENCIAS DE TRANSITO"));
        list.add(new ModulosSistemas("00100031","TIPOS DE VEICULOS"));
        list.add(new ModulosSistemas("00100032","SITUACAO DOS VEICULOS"));
        list.add(new ModulosSistemas("00100033","SELECAO DE SECOES"));
        list.add(new ModulosSistemas("00100034","GRUPOS DE MATERIAIS"));
        list.add(new ModulosSistemas("00100035","SUBGRUPOS DE MATERIAIS"));
        list.add(new ModulosSistemas("00100036","TIPOS DE CERTIDOES NEGATIVAS"));
        list.add(new ModulosSistemas("00100037","MATERIAIS"));
        list.add(new ModulosSistemas("00100038","CERTIDOES DOS FORNECEDORES"));
        list.add(new ModulosSistemas("00100039","VEICULOS"));
        list.add(new ModulosSistemas("00100040","CONSULTA COMPRAS DE MATERIAIS"));
        list.add(new ModulosSistemas("00100041","CONSULTA NOTAS FISCAIS DO MATERIAL"));
        list.add(new ModulosSistemas("00100042","SINDICATOS FUNCIONAIS"));
        list.add(new ModulosSistemas("00100043","TIPOS DE DIREITOS A RECEBER"));
        list.add(new ModulosSistemas("00100044","MODALIDADES DE LICITACAO"));
        list.add(new ModulosSistemas("00100045","NACIONALIDADES"));
        list.add(new ModulosSistemas("00100046","GRAU DE INSTRUCAO"));
        list.add(new ModulosSistemas("00100047","INSS"));
        list.add(new ModulosSistemas("00100048","IRRF"));
        list.add(new ModulosSistemas("00100049","PATRIMONIO"));
        list.add(new ModulosSistemas("00100050","PATRIMONIO VALORES"));
        list.add(new ModulosSistemas("00100051","MUNICIPIOS"));
        list.add(new ModulosSistemas("00100052","BANCOS"));
        list.add(new ModulosSistemas("00100053","ASSINATURAS DO GESTOR"));
        list.add(new ModulosSistemas("00100054","ASSINATURAS DO CONTROLADOR INTERNO"));
        list.add(new ModulosSistemas("00100055","CLASSES DE PATRIMONIO"));
        list.add(new ModulosSistemas("00100056","RESPONSAVEIS PELO PATRIMONIO"));

        list.add(new ModulosSistemas("00100057","CATEGORIAS FUNCIONAIS"));
        list.add(new ModulosSistemas("00100058","TIPOS DE ADMISSAO FUNCIONAIS"));
        list.add(new ModulosSistemas("00100059","CBO"));
        list.add(new ModulosSistemas("00100060","CARGOS"));
        list.add(new ModulosSistemas("00100061","CARGOS-VALORES"));
        list.add(new ModulosSistemas("00100062","HORARIOS"));
        list.add(new ModulosSistemas("00100063","CODIGOS DE ACUMULO PARA CEDULA C"));
        list.add(new ModulosSistemas("00100064","FORMULAS DE CALCULO"));
        list.add(new ModulosSistemas("00100065","TIPOS DE FOLHA"));
        list.add(new ModulosSistemas("00100066","SITUACAO FUNCIONAL"));
        list.add(new ModulosSistemas("00100067","TIPOS DE LICENCAS"));
        list.add(new ModulosSistemas("00100068","TIPOS DE PROVENTOS"));
        list.add(new ModulosSistemas("00100069","TIPOS DE DESCONTOS"));
        list.add(new ModulosSistemas("00100070","EVENTOS"));
        list.add(new ModulosSistemas("00100071","RECIBOS DE PAGAMENTOS (RH)"));
        list.add(new ModulosSistemas("00100072","VINCULOS EMPREGATICIOS"));
        list.add(new ModulosSistemas("00100073","CAUSAS DE RESCISOES"));
        list.add(new ModulosSistemas("00100074","REFERENCIAS DOS FUNCIONARIOS"));
        list.add(new ModulosSistemas("00100075","CARGOS-NIVEIS"));
        list.add(new ModulosSistemas("00100076","CENTROS DE CUSTOS"));
        list.add(new ModulosSistemas("00100077","TIPOS DE ADMISSOES - FUNCIONARIOS PUBLICOS"));
        list.add(new ModulosSistemas("00100078","TIPOS DE DESLIGAMENTOS (RH)"));
        list.add(new ModulosSistemas("00100079","DADOS FUNCIONAIS"));
        list.add(new ModulosSistemas("00100080","CONCURSOS"));
        list.add(new ModulosSistemas("00100081","CONCURSOS-VAGAS"));
        list.add(new ModulosSistemas("00100082","CONCURSOS-APROVADOS"));
        list.add(new ModulosSistemas("00100083","DADOS DE PENSIONISTA"));
        list.add(new ModulosSistemas("00100084","CONSULTA FUNCIONARIOS POR SECAO"));
        list.add(new ModulosSistemas("00100085","CONSULTA FUNCIONARIOS POR CARGO"));
        list.add(new ModulosSistemas("00100086","TIPOS DE DEFICIENCIAS FISICAS"));
        list.add(new ModulosSistemas("00100087","FORMACAO ACADEMICA"));
        list.add(new ModulosSistemas("00100088","FUNCIONARIOS"));
        list.add(new ModulosSistemas("00100089","FUNCIONARIOS-CENTRO DE CUSTO"));
        list.add(new ModulosSistemas("00100090","FUNCIONARIOS-OUTROS VINCULOS DE INSS"));
        list.add(new ModulosSistemas("00100091","LICENCAS"));
        list.add(new ModulosSistemas("00100092","DEPENDENTES"));
        list.add(new ModulosSistemas("00100093","FUNCIONARIOS DE FERIAS"));
        list.add(new ModulosSistemas("00100094","LANCAMENTOS MENSAIS DE EVENTOS"));
        list.add(new ModulosSistemas("00100095","CALCULO DA FOLHA"));

        return list;
    }

    public List<ModulosSistemas> getListaAll(){
        List<ModulosSistemas> list = new ArrayList<ModulosSistemas>();

        list.add(new ModulosSistemas(AvisosAcessandoSistema,"Avisos Acessando o Sistema"));
        list.add(new ModulosSistemas(Estados,"Estados"));
        list.add(new ModulosSistemas(Bairros,"Bairros"));
        list.add(new ModulosSistemas(Logradouros,"Logradouros"));
        list.add(new ModulosSistemas(Selic,"Selic"));
        list.add(new ModulosSistemas(EstadoCivil,"Estado Civil"));
        list.add(new ModulosSistemas(Pessoas,"Pessoas"));
        list.add(new ModulosSistemas(Orgaos,"Orgaos"));
        list.add(new ModulosSistemas(Unidades,"Unidades"));
        list.add(new ModulosSistemas(PlanodeContas,"Plano de Contas"));
        list.add(new ModulosSistemas(ParametrosComuns,"Parâmetros Comuns"));
        list.add(new ModulosSistemas(Funcoes,"Funcoes"));
        list.add(new ModulosSistemas(SubFuncoes,"SubFuncoes"));
        list.add(new ModulosSistemas(Programas,"Programas"));
        list.add(new ModulosSistemas(SubProgramas,"SubProgramas"));
        list.add(new ModulosSistemas(Acoes,"Acoes"));
        list.add(new ModulosSistemas(FontedeRecursos,"Fonte de Recursos"));
        list.add(new ModulosSistemas(FormasdePagamento,"Formas de Pagamento"));
        list.add(new ModulosSistemas(TiposdeReceitaDespesaExtra,"Tipos de Receita/Despesa Extra"));
        list.add(new ModulosSistemas(Moedas,"Moedas"));
        list.add(new ModulosSistemas(TiposdePatrimonio,"Tipos de Patrimonio"));
        list.add(new ModulosSistemas(AssuntosdeContratos,"Assuntos de Contratos"));
        list.add(new ModulosSistemas(TiposdeObras,"Tipos de Obras"));
        list.add(new ModulosSistemas(TiposdeArrecadacao,"Tipos de Arrecadacao"));
        list.add(new ModulosSistemas(Secoes,"Secoes"));
        list.add(new ModulosSistemas(SecoesUsuarios,"Secoes-Usuarios"));
        list.add(new ModulosSistemas(Combustiveis,"Combustiveis"));
        list.add(new ModulosSistemas(MarcasdeVeiculos,"Marcas de Veiculos"));
        list.add(new ModulosSistemas(ModelosdeVeiculos,"Modelos de Veiculos"));
        list.add(new ModulosSistemas(TiposdeOcorrenciasdeTransito,"Tipos de Ocorrencias de Transito"));
        list.add(new ModulosSistemas(TiposdeVeiculos,"Tipos de Veiculos"));
        list.add(new ModulosSistemas(SituacaodosVeiculos,"Situacao dos Veiculos"));
        list.add(new ModulosSistemas(SelecaodeSecoes,"Selecao de Secoes"));
        list.add(new ModulosSistemas(GruposdeMateriais,"Grupos de Materiais"));
        list.add(new ModulosSistemas(SubGruposdeMateriais,"SubGrupos de Materiais"));
        list.add(new ModulosSistemas(TiposdeCertidoesNegativas,"Tipos de Certidoes Negativas"));
        list.add(new ModulosSistemas(Materiais,"Materiais"));
        list.add(new ModulosSistemas(CertidoesdosFornecedores,"Certidoes dos Fornecedores"));
        list.add(new ModulosSistemas(Veiculos,"Veiculos"));
        list.add(new ModulosSistemas(ConsultaComprasMaterial,"Consulta Compras Material"));
        list.add(new ModulosSistemas(ConsultaNotasFiscaisdoMaterial,"Consulta Notas Fiscais do Material"));
//        lista.add(new ModulosSistemas(SecoesFotos,"Secoes-Fotos"));
//        lista.add(new ModulosSistemas(SecoesDadosContabeis,"Secoes-Dados Contabeis"));
        list.add(new ModulosSistemas(SindicatosFuncionais,"Sindicatos Funcionais"));
        list.add(new ModulosSistemas(TiposdeDireitosaReceber,"Tipos de Direitos a Receber"));
        list.add(new ModulosSistemas(ModalidadesdeLicitacao,"Modalidades de Licitacao"));
        list.add(new ModulosSistemas(Nacionalidades,"Nacionalidades"));
        list.add(new ModulosSistemas(GraudeInstrucao,"Grau de Instrucao"));
        list.add(new ModulosSistemas(INSS,"INSS"));
        list.add(new ModulosSistemas(IRRF,"IRRF"));
        list.add(new ModulosSistemas(Patrimonio,"Patrimonio"));
        list.add(new ModulosSistemas(PatrimonioValores,"Patrimonio-Valores"));
        list.add(new ModulosSistemas(Municipios,"Municipios"));
        list.add(new ModulosSistemas(Bancos,"Bancos"));
        list.add(new ModulosSistemas(AssinaturasGestor,"Assinaturas Gestor"));
        list.add(new ModulosSistemas(AssinaturasControladorInterno,"Assinaturas Controlador Interno"));
        list.add(new ModulosSistemas(Classesdepatrimonio,"Classes de patrimonio"));
        list.add(new ModulosSistemas(PatrimonioResponsaveis,"Patrimonio - Responsaveis"));
        list.add(new ModulosSistemas(CategoriasFuncionais,"Categorias Funcionais"));
        list.add(new ModulosSistemas(TiposdeAdmissaoFuncionais,"Tipos de Admissao Funcionais"));
        list.add(new ModulosSistemas(CBO,"CBO"));
        list.add(new ModulosSistemas(CARGOS,"CARGOS"));
        list.add(new ModulosSistemas(CARGOSVALORES,"CARGOS-VALORES"));
        list.add(new ModulosSistemas(Horarios,"Horarios"));
        list.add(new ModulosSistemas(CodigosdeAcumulosparaCedulaC,"Codigos de Acumulos para Cedula C"));
        list.add(new ModulosSistemas(FormulasdeCalculo,"Formulas de Calculo"));
        list.add(new ModulosSistemas(TiposdeFolha,"Tipos de Folha"));
        list.add(new ModulosSistemas(SituacoesFuncionais,"Situacoes Funcionais"));
        list.add(new ModulosSistemas(TiposdeLicencas,"Tipos de Licencas"));
        list.add(new ModulosSistemas(TiposdeProventos,"Tipos de Proventos"));
        list.add(new ModulosSistemas(TiposdeDescontos,"Tipos de Descontos"));
        list.add(new ModulosSistemas(Eventos,"Eventos"));
        list.add(new ModulosSistemas(RecibosdePagamentoRH,"Recibos de Pagamento (RH)"));
        list.add(new ModulosSistemas(VinculosEmpregaticios,"Vinculos Empregaticios"));
        list.add(new ModulosSistemas(CausasdeRescisoes,"Causas de Rescisoes"));
        list.add(new ModulosSistemas(ReferenciasdosFuncionarios,"Referencias dos Funcionarios"));
        list.add(new ModulosSistemas(CARGOSNIVEIS,"CARGOS-NIVEIS"));
        list.add(new ModulosSistemas(CentrosdeCustos,"Centros de Custos"));
        list.add(new ModulosSistemas(TiposdeAdmissoesFuncionariosPublicos,"Tipos de Admissoes - Funcionarios Publicos"));
        list.add(new ModulosSistemas(TiposdeDesligamentosRH,"Tipos de Desligamentos (RH)"));
        list.add(new ModulosSistemas(Dadosfuncionais,"Dados funcionais"));
        list.add(new ModulosSistemas(Concursos,"Concursos"));
        list.add(new ModulosSistemas(ConcursosVagas,"Concursos-Vagas"));
        list.add(new ModulosSistemas(ConcursosAprovados,"Concursos-Aprovados"));
        list.add(new ModulosSistemas(DadosdePensionista,"Dados de Pensionista"));
        list.add(new ModulosSistemas(ConsultaFuncionariosporSecao,"Consulta Funcionarios por Secao"));
        list.add(new ModulosSistemas(ConsultaFuncionariosporCargo,"Consulta Funcionarios por Cargo"));
        list.add(new ModulosSistemas(TiposdeDeficienciasFisicas,"Tipos de Deficiencias Fisicas"));
        list.add(new ModulosSistemas(FormacaoAcademica,"Formacao Academica"));
        list.add(new ModulosSistemas(Funcionarios,"Funcionarios"));
        list.add(new ModulosSistemas(FuncionariosCentrodeCusto,"Funcionarios-Centro de Custo"));
        list.add(new ModulosSistemas(OutrosVinculosdeINSS,"Outros Vinculos de INSS"));
        list.add(new ModulosSistemas(Licencas,"Licencas"));
        list.add(new ModulosSistemas(Dependentes,"Dependentes"));
        list.add(new ModulosSistemas(FuncionariosdeFerias,"Funcionarios de Ferias"));
        list.add(new ModulosSistemas(LancamentosMensaisdeEventos,"Lancamentos Mensais de Eventos"));
        list.add(new ModulosSistemas(CalculodaFolha,"Calculo da Folha"));
        list.add(new ModulosSistemas(CARGOSCLASSES,"CARGOS-CLASSES"));
        list.add(new ModulosSistemas(UnidadesdeMedidasdeObras,"Unidades de Medidas de Obras"));
        list.add(new ModulosSistemas(CNAE,"CNAE"));
        list.add(new ModulosSistemas(Eventoscontabeis,"Eventos contabeis"));
        list.add(new ModulosSistemas(SituacaoPatrimonio,"Situação Patrimônio"));
        list.add(new ModulosSistemas(AssinaturasEspecificas,"Assinaturas Específicas"));
        list.add(new ModulosSistemas(AgenciasBancarias,"Agências Bancárias"));

        list.add(new ModulosSistemas(AssuntosdeProcessos,"Assuntos de Processos"));
        list.add(new ModulosSistemas(Correspondencias,"Correspondencias"));
        list.add(new ModulosSistemas(Processos,"Processos"));
        list.add(new ModulosSistemas(PreProcessos,"Pré Processos"));
        list.add(new ModulosSistemas(EnvioProcessos,"Envio Processos"));
        list.add(new ModulosSistemas(RecebimentoProcessos,"Recebimento Processos"));
        list.add(new ModulosSistemas(MovimentosProcessos,"Movimentos Processos"));
        list.add(new ModulosSistemas(FornecedoresdoProcesso,"Fornecedores do Processo"));
        list.add(new ModulosSistemas(ParametrosProtocolo,"Parametros-Protocolo"));
        list.add(new ModulosSistemas(MovimentosCorrespondencias,"Movimentos Correspondencias"));
        list.add(new ModulosSistemas(EnvioCorrespondencias,"Envio Correspondencias"));
        list.add(new ModulosSistemas(RecebimentoCorrespondencias,"Recebimento Correspondencias"));

        list.add(new ModulosSistemas(OrcamentoLeis,"Orcamento-Leis"));
        list.add(new ModulosSistemas(AutorizacaoOrcamentaria,"Autorizacao Orcamentaria"));
        list.add(new ModulosSistemas(OrcamentoDotacoes,"Orcamento-Dotacoes"));
        list.add(new ModulosSistemas(OrcamentoReceitasPrevistas,"Orcamento-Receitas Previstas"));
        list.add(new ModulosSistemas(OrcamentoTotalizaDespesas,"Orcamento-Totaliza Despesas"));
        list.add(new ModulosSistemas(HistoricosPadroes,"Historicos Padroes"));
        list.add(new ModulosSistemas(Licitacao,"Licitacao"));
        list.add(new ModulosSistemas(Obras,"Obras"));
        list.add(new ModulosSistemas(Contratos,"Contratos"));
        list.add(new ModulosSistemas(DividaFundada,"Divida Fundada"));
        list.add(new ModulosSistemas(MovimentosdoAtivoRealizavel,"Movimentos do Ativo Realizavel"));
        list.add(new ModulosSistemas(PreEmpenhos,"Pre-Empenhos"));
        list.add(new ModulosSistemas(Empenhos,"Empenhos"));
        list.add(new ModulosSistemas(EmpenhosNotasFiscais,"Empenhos - Notas Fiscais"));
        list.add(new ModulosSistemas(EmpenhosLiquidacaoEstorno,"Empenhos - Liquidacao Estorno"));
        list.add(new ModulosSistemas(EmpenhosAnulacao,"Empenhos - Anulacao"));
        list.add(new ModulosSistemas(SubEmpenhos,"SubEmpenhos"));
        list.add(new ModulosSistemas(OrcamentoPPAIndicadoresdeProgramas,"Orcamento-PPA-Indicadores de Programas"));
        list.add(new ModulosSistemas(OrcamentoPPAPlanoPlurianual,"Orcamento-PPA-Plano Plurianual"));
        list.add(new ModulosSistemas(Suplementacoes,"Suplementacoes"));
        list.add(new ModulosSistemas(RestosEmpenhos,"Restos-Empenhos"));
        list.add(new ModulosSistemas(VariacoesPatrimoniais,"Variacoes Patrimoniais"));
        list.add(new ModulosSistemas(MovimentosdasVariacoesPatrimoniais,"Movimentos das Variacoes Patrimoniais"));
        list.add(new ModulosSistemas(ParametrosContabilidade,"Parametros-Contabilidade"));
        list.add(new ModulosSistemas(ParametrosdosOrgaos,"Parametros dos Orgaos"));
        list.add(new ModulosSistemas(Reducoes,"Reducoes"));
        list.add(new ModulosSistemas(FichaOrcamentaria,"Ficha Orcamentaria"));
        list.add(new ModulosSistemas(GerarBalancete,"Gerar Balancete"));
        list.add(new ModulosSistemas(ReceitaExtraOrcamentaria,"Receita Extra-Orcamentaria"));
        list.add(new ModulosSistemas(AlienacaodeBens,"Alienacao de Bens"));
        list.add(new ModulosSistemas(AplicacaoFinanceira,"Aplicacao Financeira"));
        list.add(new ModulosSistemas(Tiposdesuplementacao,"Tipos de suplementacao"));
        list.add(new ModulosSistemas(LancamentosContabeis,"Lancamentos Contabeis"));
        list.add(new ModulosSistemas(RestosAnulacaodeEmpenhos,"Restos-Anulacao de Empenhos"));
        list.add(new ModulosSistemas(ImpressaoGeraldeCheques,"Impressao Geral de Cheques"));
        list.add(new ModulosSistemas(MovimentosContabeis,"Movimentos Contabeis"));
        list.add(new ModulosSistemas(AbrirnovoOrcamento,"Abrir novo Orcamento"));
        list.add(new ModulosSistemas(CaracteristicasPeculiardosEmpenhos,"Caracteristicas Peculiar dos Empenhos"));
        list.add(new ModulosSistemas(GruposdeReceitaDespesaExtra,"Grupos de Receita/Despesa Extra"));
        list.add(new ModulosSistemas(CancelamentosExtraOrcamentarios,"Cancelamentos Extra-Orcamentarios"));
        list.add(new ModulosSistemas(LimitesdeSuplementacoes,"Limites de Suplementacoes"));
        list.add(new ModulosSistemas(CaracteristicasPeculiardaReceita,"Caracteristicas Peculiar da Receita"));
        list.add(new ModulosSistemas(DireitosaReceber,"Direitos a Receber"));
        list.add(new ModulosSistemas(LancamentosContabeisdoSistema,"Lancamentos Contabeis do Sistema"));
        list.add(new ModulosSistemas(Convenios,"Convenios"));
        list.add(new ModulosSistemas(ParticipantesdeConvenios,"Participantes de Convenios"));
        list.add(new ModulosSistemas(OrdensdePagamento,"Ordens de Pagamento"));
        list.add(new ModulosSistemas(Retencoes,"Retencoes"));
        list.add(new ModulosSistemas(PreOrdensdePagamentoQuitacao,"Pre-Ordens de Pagamento-Quitacao"));
        list.add(new ModulosSistemas(PreOrdensdePagamento,"Pre-Ordens de Pagamento"));
        list.add(new ModulosSistemas(EmpenhosLiquidacao,"Empenhos - Liquidacao"));
        list.add(new ModulosSistemas(EmpenhosdeRestosLiquidacao,"Empenhos de Restos - Liquidacao"));
        list.add(new ModulosSistemas(RestosPreOrdensdePagamento,"Restos-Pre Ordens de Pagamento"));
        list.add(new ModulosSistemas(RestosPreOrdensdePagtoQuitacao,"Restos-Pre Ordens de Pagto - Quitacao"));
        list.add(new ModulosSistemas(RestosOrdensdePagamento,"Restos-Ordens de Pagamento"));
        list.add(new ModulosSistemas(EstornodeOrdensdePagamentoGuiasdeRecolhimento,"Estorno de Ordens de Pagamento (Guias de Recolhimento)"));
        list.add(new ModulosSistemas(ContabilidadeArrecadacao,"Contabilidade-Arrecadacao"));
        list.add(new ModulosSistemas(EstornodeArrecadacao,"Estorno de Arrecadacao"));
        list.add(new ModulosSistemas(ContabilidadeConciliacaoBancaria,"Contabilidade-Conciliacao Bancária"));
        list.add(new ModulosSistemas(ContabilidadeTransferenciasBancarias,"Contabilidade-Transferencias Bancárias"));
        list.add(new ModulosSistemas(PreOrdensdePagamentoDespesaExtra,"Pre-Ordens de Pagamento - Despesa Extra"));
        list.add(new ModulosSistemas(PreOrdensdePagamentoDespesaExtraQuitacao,"Pre-Ordens de Pagamento Despesa Extra - Quitacao"));
        list.add(new ModulosSistemas(DespesaExtraOrcamentaria,"Despesa Extra-Orcamentaria"));
        list.add(new ModulosSistemas(RestosGuiadeRecolhimento,"Restos-Guia de Recolhimento"));
        list.add(new ModulosSistemas(ContabilidadeCheques,"Contabilidade-Cheques"));
        list.add(new ModulosSistemas(ContabilidadeCompensacaodeCheques,"Contabilidade-Compensacao de Cheques"));
        list.add(new ModulosSistemas(RemecasBancarias,"Remeças Bancárias"));

        list.add(new ModulosSistemas(Abastecimentos,"Abastecimentos"));
        list.add(new ModulosSistemas(ManutencoesemVeiculos,"Manutencoes em Veiculos"));
        list.add(new ModulosSistemas(EmpenhosFrotas,"Empenhos-Frotas"));
        list.add(new ModulosSistemas(DeslocamentosdeVeiculos,"Deslocamentos de Veiculos"));
        list.add(new ModulosSistemas(ParametrosFrotas,"Parametros-Frotas"));
        list.add(new ModulosSistemas(Ocorrenciasdetransito,"Ocorrencias de transito"));

        list.add(new ModulosSistemas(OutraPrevidencia,"Outra Previdencia"));
        list.add(new ModulosSistemas(ExpressoesSQL,"Expressoes SQL"));
        list.add(new ModulosSistemas(UFIR,"UFIR"));
        list.add(new ModulosSistemas(GPSFPAS,"GPS/FPAS"));
        list.add(new ModulosSistemas(ValeTransporteValeRefeicao,"Vale Transporte/Vale Refeicao"));
        list.add(new ModulosSistemas(TabeladeAbatimentodeFaltas,"Tabela de Abatimento de Faltas"));
        list.add(new ModulosSistemas(TiposdeAtos,"Tipos de Atos"));
        list.add(new ModulosSistemas(TiposdeMovimentacoesdepessoal,"Tipos de Movimentacoes de pessoal"));
        list.add(new ModulosSistemas(DuplicarDadosFuncionais,"Duplicar Dados Funcionais"));
        list.add(new ModulosSistemas(DuplicarumaReferencia,"Duplicar uma Referencia"));
        list.add(new ModulosSistemas(CedulaC,"Cedula C"));
        list.add(new ModulosSistemas(ConsultaHistoricoFerias,"Consulta Historico Ferias"));
        list.add(new ModulosSistemas(Rescisoes,"Rescisoes"));
        list.add(new ModulosSistemas(VencimentosVariaveis,"Vencimentos Variaveis"));
        list.add(new ModulosSistemas(Cadastrodeprestadoresdeservico,"Cadastro de prestadores de servico"));
        list.add(new ModulosSistemas(PrestadorServicosMovimentacao,"Prestador Servicos - Movimentacao"));
        list.add(new ModulosSistemas(EmpenhosdaFolha,"Empenhos da Folha"));
        list.add(new ModulosSistemas(MovimentacaodePessoal,"Movimentacao de Pessoal"));
        list.add(new ModulosSistemas(CompensacaocomoINSS,"Compensacao com o INSS"));
        list.add(new ModulosSistemas(ParametrosFolha,"Parametros - Folha"));
        list.add(new ModulosSistemas(GPS,"GPS"));
        list.add(new ModulosSistemas(Fechamentomensal,"Fechamento mensal"));
        list.add(new ModulosSistemas(GerarEmpenhosparaContabilidade,"Gerar Empenhos para Contabilidade"));
        list.add(new ModulosSistemas(AlteracoesdeChavesparaGoias,"Alteracoes de Chaves para Goias"));
        list.add(new ModulosSistemas(CentrodeCustodePagamento,"Centro de Custo de Pagamento"));


        list.add(new ModulosSistemas(ItensdaNotaFiscal,"Itens da Nota Fiscal"));
        list.add(new ModulosSistemas(MovimentacaodoEstoque,"Movimentacao do Estoque"));
        list.add(new ModulosSistemas(AcertodeEstoque,"Acerto de Estoque"));
        list.add(new ModulosSistemas(EntradanoEstoque,"Entrada no Estoque"));
        list.add(new ModulosSistemas(SaidadoEstoque,"Saida do Estoque"));
        list.add(new ModulosSistemas(EmprestimosDevolucoesentreCentrosdeCusto,"Emprestimos/Devolucoes entre Centros de Custo"));
        list.add(new ModulosSistemas(EstoqueporSecao,"Estoque por Secao"));
        list.add(new ModulosSistemas(RequisicaodeMateriais,"Requisicao de Materiais"));
        list.add(new ModulosSistemas(RequisicaodeMateriaisItens,"Requisicao de Materiais-Itens"));
        list.add(new ModulosSistemas(BaixasemRequisicoesdeMateriais,"Baixas em Requisicoes de Materiais"));
        list.add(new ModulosSistemas(SolicitacaodeCompras,"Solicitacao de Compras"));
        list.add(new ModulosSistemas(SolicitacaodeComprasItens,"Solicitacao de Compras-Itens"));
        list.add(new ModulosSistemas(NotasFiscais,"Notas Fiscais"));
        list.add(new ModulosSistemas(NotasFiscaisItens,"Notas Fiscais - Itens"));
        list.add(new ModulosSistemas(RequisicaodeCompras,"Requisicao de Compras"));
        list.add(new ModulosSistemas(RequisicaodeComprasItens,"Requisicao de Compras - Itens"));
        list.add(new ModulosSistemas(CompraRapida,"Compra Rapida"));
        list.add(new ModulosSistemas(ProcessodeComprasGeral,"Processo de Compras - Geral"));
        list.add(new ModulosSistemas(ProcessodeComprasSolicitacoes,"Processo de Compras - Solicitacoes"));
        list.add(new ModulosSistemas(ProcessodeComprasItens,"Processo de Compras - Itens"));
        list.add(new ModulosSistemas(ProcessodeComprasFornecedores,"Processo de Compras - Fornecedores"));
        list.add(new ModulosSistemas(ProcessodeComprasCotacoes,"Processo de Compras - Cotacoes"));
        list.add(new ModulosSistemas(TiposdeLicitacoes,"Tipos de Licitacoes"));

        list.add(new ModulosSistemas(CadastrosTributos,"Cadastros-Tributos"));
        list.add(new ModulosSistemas(CadastrosRubricas,"Cadastros-Rubricas"));
        list.add(new ModulosSistemas(Tiposdesociedades,"Tipos de sociedades"));
        list.add(new ModulosSistemas(Fiscais,"Fiscais"));
        list.add(new ModulosSistemas(UFM,"UFM"));
        list.add(new ModulosSistemas(TiposdeServicos,"Tipos de Servicos"));
        list.add(new ModulosSistemas(Contribuintes,"Contribuintes"));
        list.add(new ModulosSistemas(ContribuintesFinanceiros,"Contribuintes Financeiros"));
        list.add(new ModulosSistemas(ContribuintesLancamentosQuitacoes,"Contribuintes Lancamentos Quitacoes"));
        list.add(new ModulosSistemas(NotasFiscaisEmitidasporContribuintes,"Notas Fiscais Emitidas por Contribuintes"));
        list.add(new ModulosSistemas(EmitirAlvaraparaContribuintes,"Emitir Alvara para Contribuintes"));
        list.add(new ModulosSistemas(CadastrosUsuariosNotaAvulsa,"Cadastros-Usuarios Nota Avulsa"));
        list.add(new ModulosSistemas(Imoveis,"Imoveis"));
        list.add(new ModulosSistemas(ImoveisCaracteristicas,"Imoveis Caracteristicas"));
        list.add(new ModulosSistemas(ImoveisFinanceiros,"Imoveis Financeiros"));
        list.add(new ModulosSistemas(ImoveisLancamentosQuitacao,"Imoveis Lancamentos Quitacao"));
        list.add(new ModulosSistemas(ImoveisGerarDAM,"Imoveis Gerar DAM"));
        list.add(new ModulosSistemas(ImpressaodeDeclaracaodeIsento,"Impressao de Declaracao de Isento"));
        list.add(new ModulosSistemas(PlantadeValoresdeIPTUNormal,"Planta de Valores de IPTU-Normal"));
        list.add(new ModulosSistemas(PlantadeValoresdeIPTUZoneamento,"Planta de Valores de IPTU-Zoneamento"));
        list.add(new ModulosSistemas(PlantadeValoresdeIPTULogradouro,"Planta de Valores de IPTU-Logradouro"));
        list.add(new ModulosSistemas(PlantadeValoresdeIPTUZonaLogradouros,"Planta de Valores de IPTU-Zona/Logradouros"));
        list.add(new ModulosSistemas(InformacoesTerrenoIPTU,"Informacoes Terreno-IPTU"));
        list.add(new ModulosSistemas(InformacoesEdificacaoIPTU,"Informacoes Edificacao-IPTU"));
        list.add(new ModulosSistemas(ItensBasicosIPTU,"Itens Basicos IPTU"));
        list.add(new ModulosSistemas(AliquotasIPTU,"Aliquotas IPTU"));
        list.add(new ModulosSistemas(AliquotasIPTUConstrucao,"Aliquotas IPTU-Construcao"));
        list.add(new ModulosSistemas(DescontosdeIPTUporCondicoes,"Descontos de IPTU por Condicoes"));
        list.add(new ModulosSistemas(VencimentoParcelasIPTU,"Vencimento Parcelas IPTU"));
        list.add(new ModulosSistemas(ValoresTSUporm2,"Valores TSU por m2"));
        list.add(new ModulosSistemas(ValoresConstrucaoporTipo,"Valores Construcao por Tipo"));
        list.add(new ModulosSistemas(PlantadeValoresRurais,"Planta de Valores Rurais"));
        list.add(new ModulosSistemas(InformacoesImoveisItens,"Informacoes Imoveis-Itens"));
        list.add(new ModulosSistemas(InformacoesImoveisSubItens,"Informacoes Imoveis-SubItens"));
        list.add(new ModulosSistemas(FatordeCorrecaodeGlebas,"Fator de Correcao de Glebas"));
        list.add(new ModulosSistemas(TabeladeTaxadeIluminacaoPublica,"Tabela de Taxa de Iluminacao Publica"));
        list.add(new ModulosSistemas(TSUporFormula,"TSU - por Formula"));
        list.add(new ModulosSistemas(VencimentosAlvaraAnual,"Vencimentos Alvara Anual"));
        list.add(new ModulosSistemas(CadastrosTaxas,"Cadastros - Taxas"));
        list.add(new ModulosSistemas(TiposdeTransmissoesITBI,"Tipos de Transmissoes ITBI"));
        list.add(new ModulosSistemas(TiposdeIsencoes,"Tipos de Isencoes"));
        list.add(new ModulosSistemas(TabeladeAnistiaFiscal,"Tabela de Anistia Fiscal"));
        list.add(new ModulosSistemas(CadastrosDespesasMapaApuracaodeDespesas,"Cadastros-Despesas Mapa Apuracao de Despesas"));
        list.add(new ModulosSistemas(TabeladeMultaseJurosporTributo,"Tabela de Multas e Juros por Tributo"));
        list.add(new ModulosSistemas(FatordeLocalizacaodeTaxas,"Fator de Localizacao de Taxas"));
        list.add(new ModulosSistemas(ExtratodoContribuinte,"Extrato do Contribuinte"));
        list.add(new ModulosSistemas(TabelaMensagensExtranoDAM,"Tabela Mensagens Extra no DAM"));
        list.add(new ModulosSistemas(Isencoesdecontribuintes,"Isencoes de contribuintes"));
        list.add(new ModulosSistemas(TiposdeTarefas,"Tipos de Tarefas"));
        list.add(new ModulosSistemas(FinalidadesdeCND,"Finalidades de CND"));
        list.add(new ModulosSistemas(ManutencaoCertidoesNegativas,"Manutencao Certidoes Negativas"));
        list.add(new ModulosSistemas(GerarDAMsdeIPTUdetodos,"Gerar DAMs de IPTU de todos"));
        list.add(new ModulosSistemas(GerarDAMsdeISSdetodos,"Gerar DAMs de ISS de todos"));
        list.add(new ModulosSistemas(GerarDAMsdeIPTUparaCarne,"Gerar DAMs de IPTU para Carne"));
        list.add(new ModulosSistemas(DAMSdeITBI,"DAMS de ITBI"));
        list.add(new ModulosSistemas(DAMSdeITBIRural,"DAMS de ITBI Rural"));
        list.add(new ModulosSistemas(DAMSdeTaxas,"DAMS de Taxas"));
        list.add(new ModulosSistemas(DAMSdeISS,"DAMS de ISS"));
        list.add(new ModulosSistemas(DAMSdeISSporPeriodo,"DAMS de ISS por Periodo"));
        list.add(new ModulosSistemas(DAMSdeTaxadeAlvaraTodos,"DAMS de Taxa de Alvara (todos)"));
        list.add(new ModulosSistemas(NotaAvulsaManutencao,"Nota Avulsa Manutencao"));
        list.add(new ModulosSistemas(NotaAvulsaManutencaonositens,"Nota Avulsa Manutencao nos itens"));
        list.add(new ModulosSistemas(BlocosdeNotasFiscais,"Blocos de Notas Fiscais"));
        list.add(new ModulosSistemas(CancelamentodeBlocosdeNotasFiscais,"Cancelamento de Blocos de Notas Fiscais"));
        list.add(new ModulosSistemas(OrdensdeServico,"Ordens de Servico"));
        list.add(new ModulosSistemas(OrdensdeServicodePosturas,"Ordens de Servico de Posturas"));
        list.add(new ModulosSistemas(RocagemdeLotes,"Rocagem de Lotes"));
        list.add(new ModulosSistemas(AutodeInfracaodeContribuintes,"Auto de Infracao de Contribuintes"));
        list.add(new ModulosSistemas(GuiadeFiscalizacao,"Guia de Fiscalizacao"));
        list.add(new ModulosSistemas(GuiadeFiscalizacaoManutencaoemitens,"Guia de Fiscalizacao Manutencao em itens"));
        list.add(new ModulosSistemas(GuiadeAtualizacaoFiscal,"Guia de Atualizacao Fiscal"));
        list.add(new ModulosSistemas(GuiadeAtualizacaoFiscalManutencaoemitens,"Guia de Atualizacao Fiscal Manutencao em itens "));
        list.add(new ModulosSistemas(ProcessosdeContribuintes,"Processos de Contribuintes"));
        list.add(new ModulosSistemas(MovimentacaodeProcessosdeContribuintes,"Movimentacao de Processos de Contribuintes"));
        list.add(new ModulosSistemas(ProcessosdeImoveis,"Processos de Imoveis"));
        list.add(new ModulosSistemas(MovimentacaodeProcessosdeImoveis,"Movimentacao de Processos de Imoveis"));
        list.add(new ModulosSistemas(ProcessosdePessoas,"Processos de Pessoas"));
        list.add(new ModulosSistemas(MovimentacaodeProcessosdePessoas,"Movimentacao de Processos de Pessoas"));
        list.add(new ModulosSistemas(RegistrodeMarcas,"Registro de Marcas"));
        list.add(new ModulosSistemas(ParcelamentodeISS,"Parcelamento de ISS"));
        list.add(new ModulosSistemas(ParcelamentodeISSManutencaoemitens,"Parcelamento de ISS Manutencao em itens"));
        list.add(new ModulosSistemas(ParcelamentodeIPTU,"Parcelamento de IPTU"));
        list.add(new ModulosSistemas(ParcelamentodeIPTUManutencaoemitens,"Parcelamento de IPTU Manutencao em itens"));
        list.add(new ModulosSistemas(ImpressaodeCertidoesNegativas,"Impressao de Certidoes Negativas"));
        list.add(new ModulosSistemas(ImpressaodeEscriturasdedoacaodeImoveis,"Impressao de Escrituras de doacao de Imoveis"));
        list.add(new ModulosSistemas(ImpressaodeEscriturasdecompraevendadeImoveis,"Impressao de Escrituras de compra e venda de Imoveis"));
        list.add(new ModulosSistemas(MapadeApuracaodeDespesas,"Mapa de Apuracao de Despesas"));
        list.add(new ModulosSistemas(TSUColetadelixo,"TSU-Coleta de lixo"));
        list.add(new ModulosSistemas(ValidarCertidaoNegativa,"Validar Certidao Negativa"));
        list.add(new ModulosSistemas(IsencoesdeImoveis,"Isencoes de Imoveis"));
        list.add(new ModulosSistemas(MovimentoNulodeISS,"Movimento Nulo de ISS"));
        list.add(new ModulosSistemas(DAMsAvulsosdeIPTU,"DAMs Avulsos de IPTU"));
        list.add(new ModulosSistemas(DAMsAvulsosdeTaxas,"DAMs Avulsos de Taxas"));
        list.add(new ModulosSistemas(DAMsLivres,"DAMs Livres"));
        list.add(new ModulosSistemas(DocumentosdeArrecadacao,"Documentos de Arrecadacao"));
        list.add(new ModulosSistemas(BaixaManualdeDams,"Baixa Manual de Dams"));
        list.add(new ModulosSistemas(BaixaAutomaticadeDams,"Baixa Automatica de Dams"));
        list.add(new ModulosSistemas(DividaEliminada,"Divida Eliminada"));
        list.add(new ModulosSistemas(ProcuraDívidaTextos,"Procura Dívida Textos"));
        list.add(new ModulosSistemas(DividaAtivaPreparaparaInscricao,"Divida Ativa - Prepara para Inscricao"));
        list.add(new ModulosSistemas(DividaAtivaLivros,"Divida Ativa - Livros"));
        list.add(new ModulosSistemas(DividaAtivaCertidoesIPTU,"Divida Ativa - Certidoes IPTU"));
        list.add(new ModulosSistemas(DividaAtivaCertidoesIPTUReferencias,"Divida Ativa - Certidoes IPTU-Referencias"));
        list.add(new ModulosSistemas(DividaAtivaInscricaoIPTU,"Divida Ativa - Inscricao IPTU"));
        list.add(new ModulosSistemas(DividaAtivaCertidoesContribuintes,"Divida Ativa - Certidoes Contribuintes"));
        list.add(new ModulosSistemas(DividaAtivaCertidoesContribuintesReferencias,"Divida Ativa - Certidoes Contribuintes-Referencias"));
        list.add(new ModulosSistemas(DividaAtivaInscricaoTaxaAlvara,"Divida Ativa - Inscricao Taxa Alvara"));
        list.add(new ModulosSistemas(ParametrosSAM,"Parametros-SAM"));
        list.add(new ModulosSistemas(RelatoriosIPTUCarnes,"Relatorios - IPTU - Carnes"));
        list.add(new ModulosSistemas(RelatoriosIPTUImpressaodeDAMs,"Relatorios - IPTU - Impressao de DAMs"));
        list.add(new ModulosSistemas(RelatoriosISSCarnes,"Relatorios - ISS - Carnes"));
        list.add(new ModulosSistemas(InformacoesImoveisGrupos,"Informacoes Imoveis-Grupos"));
        list.add(new ModulosSistemas(Zoneamentos,"Zoneamentos"));
        list.add(new ModulosSistemas(Loteamentos,"Loteamentos"));
        list.add(new ModulosSistemas(Condominios,"Condominios"));
        list.add(new ModulosSistemas(TributosReceitacontabeis,"Tributos-Receita contabeis"));
        list.add(new ModulosSistemas(ComposicaodoIPTU,"Composicao do IPTU"));
        list.add(new ModulosSistemas(GerarDAMsdeIPTU,"Gerar DAMs de IPTU"));
        list.add(new ModulosSistemas(ValorM2deConstrucaoporArea,"Valor M2 de Construcao por Area"));
        list.add(new ModulosSistemas(PlantadeValoresdeRocagemdeLotes,"Planta de Valores de Rocagem de Lotes"));
        list.add(new ModulosSistemas(LegislacaodeNotaAvulsa,"Legislacao de Nota Avulsa"));
        list.add(new ModulosSistemas(FecharExercicio,"Fechar Exercicio"));
        list.add(new ModulosSistemas(Alvaradeconstrucao,"Alvara de construcao"));
        list.add(new ModulosSistemas(Fatordecorrecaoporareacontruida,"Fator de correcao por area contruida"));
        list.add(new ModulosSistemas(Valorm2deconstrucaoporCondicoes,"Valor m2 de construcao por Condicoes"));
        list.add(new ModulosSistemas(Fatordecorrecaoporcondicoes,"Fator de correcao por condicoes"));
        list.add(new ModulosSistemas(DividasSuspensas,"Dividas Suspensas"));
        list.add(new ModulosSistemas(FinanceirosPessoas,"Financeiros Pessoas"));
        list.add(new ModulosSistemas(ValorM2ConstrucaoPontos,"Valor M2 de Construção por Pontos"));
        list.add(new ModulosSistemas(ImoveisRurais,"Imóveis Rurais"));
        list.add(new ModulosSistemas(DAMsTaxasEventuais,"DAMs Taxas Eventuais"));
        list.add(new ModulosSistemas(NFSeEfetivarContribuintes,"NFSE-Efetivar contribuintes"));

        list.add(new ModulosSistemas(Imagemdolocal,"Imagem do local"));
        list.add(new ModulosSistemas(MovimentacaodoPatrimonio,"Movimentacao do Patrimonio"));
        list.add(new ModulosSistemas(PesquisaTermodeEntrega,"Pesquisa Termo de Entrega"));
        list.add(new ModulosSistemas(TermodeEntregadeBens,"Termo de Entrega de Bens"));
        list.add(new ModulosSistemas(ParametrosPatrimonio,"Parametros-Patrimonio"));

        list.add(new ModulosSistemas(FinanceiroParametros,"Financeiro-Parametros"));
        list.add(new ModulosSistemas(CadastrosTiposdeReceitas,"Cadastros-Tipos de Receitas"));
        list.add(new ModulosSistemas(CadastrosTiposdeDespesas,"Cadastros-Tipos de Despesas"));
        list.add(new ModulosSistemas(CadastrosFormasdePagamento,"Cadastros-Formas de Pagamento"));
        list.add(new ModulosSistemas(FinanceiroContasbancarias,"Financeiro-Contas Bancárias"));
        list.add(new ModulosSistemas(Receitas,"Receitas"));
        list.add(new ModulosSistemas(Despesas,"Despesas"));
        list.add(new ModulosSistemas(TransferenciasBancarias,"Transferencias Bancárias"));
        list.add(new ModulosSistemas(ConsultaContasBancarias,"Consulta Contas Bancárias"));
        list.add(new ModulosSistemas(PrevisaodeReceitas,"Previsão de Receitas"));
        list.add(new ModulosSistemas(PrevisaodeDespesas,"Previsão de Despesas"));
        list.add(new ModulosSistemas(Compensacaodecheques,"Compensacao de cheques"));
        list.add(new ModulosSistemas(RelatoriosDespesasGeralporPeriodo,"Relatorios Despesas Geral por Periodo"));
        list.add(new ModulosSistemas(RelatoriosDespesasPrevistasporPeriodo,"Relatorios Despesas Previstas por Periodo"));
        list.add(new ModulosSistemas(RelatoriosDespesasGeralporPeriodoFornecedor,"Relatorios Despesas Geral por Periodo/Fornecedor"));
        list.add(new ModulosSistemas(RelatoriosDespesasporTipodeDespesa,"Relatorios Despesas por Tipo de Despesa"));
        list.add(new ModulosSistemas(RelatoriosReceitasGeralporPeriodo,"Relatorios Receitas Geral por Periodo"));
        list.add(new ModulosSistemas(RelatoriosReceitasPrevistasporPeriodo,"Relatorios Receitas Previstas por Periodo"));
        list.add(new ModulosSistemas(RelatoriosReceitasExtratoporTipo,"Relatorios Receitas Extrato por Tipo"));
        list.add(new ModulosSistemas(RelatoriosExtratoBancario,"Relatorios Extrato Bancário"));
        list.add(new ModulosSistemas(RelatoriosImpressaodeCheques,"Relatorios Impressao de Cheques"));
        list.add(new ModulosSistemas(RelatoriosSaldosBancarios,"Relatorios Saldos Bancários"));
        list.add(new ModulosSistemas(RelatoriosConciliacaoBancaria,"Relatorios Conciliacao Bancária"));
        list.add(new ModulosSistemas(RelatoriosPrevisaoGeral,"Relatorios Previsão Geral"));
        list.add(new ModulosSistemas(RelatoriosPrevisaoDespesa,"Relatorios Previsão Despesa"));
        list.add(new ModulosSistemas(RelatoriosDespesasResumoTipo,"Relatorios Despesas Resumo por tipo"));
        list.add(new ModulosSistemas(RelatoriosDespesasPeriodoContaBancaria,"Relatórios Despesas por Período e Conta Bancária"));
        list.add(new ModulosSistemas(RelatoriosDespesasPeriodoFonteRecurso,"Relatórios Despesas por Período e Fonte de Recurso"));
        list.add(new ModulosSistemas(RelatoriosReceitasPeriodoFonteRecurso,"Relatórios Receitas por Período e Fonte de Recurso"));

        return list;
    }
    
}
